### ISSUE TITLE
Cannot build the examples on Ubuntu 16.04

### ISSUE THREAD

**Issue by esimov** [nannou-org/nannou#735]
I was trying to build the examples, but I was getting the following error:

```
error[E0599]: no method named `to_rgba8` found for reference `&DynamicImage` in the current scope
   --> nannou/src/wgpu/texture/image.rs:511:29
    |
511 |             let img = image.to_rgba8();
    |                             ^^^^^^^^ help: there is an associated function with a similar name: `to_rgba`

error[E0599]: no method named `to_bgra8` found for reference `&DynamicImage` in the current scope
   --> nannou/src/wgpu/texture/image.rs:515:29
    |
515 |             let img = image.to_bgra8();
    |                             ^^^^^^^^ help: there is an associated function with a similar name: `to_bgra`

error[E0599]: no method named `to_rgba8` found for reference `&DynamicImage` in the current scope
   --> nannou/src/wgpu/texture/image.rs:520:29
    |
520 |             let img = image.to_rgba8();
    |                             ^^^^^^^^ help: there is an associated function with a similar name: `to_rgba`

error: aborting due to 3 previous errors
```

If I'm changing `rgba8` to `rbga` it builds, but still I'm getting the following error:

```
thread 'main' panicked at 'could not build default app window: NoAvailableAdapter', /home/esimov/Projects/Rust/nannou/nannou/src/app.rs:479:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by danwilhelm** [comment]
Your computer may have two or more graphics adapters. In this case, nannou can accidentally choose the wrong one. By default when selecting an adapter, it uses `PowerPreference::HighPerformance` to select an adapter. So when initializing your window you can try the other option, `PowerPreference::LowPower`. For example:

```
app.new_window()
    .size(512, 512)
    .view(view)
    .power_preference(PowerPreference::LowPower)
    .build().unwrap();
```

If this still does not work, you would have to enumerate all adapters and manually choose the correct one.

**Comment by mitchmindtree** [comment]
Also, these earlier compiler errors (`error[E0599]: no method named `to_rgba8` found for reference `&DynamicImage` in the current scope`) might imply that you have an older version of one of the dependencies, as I believe `to_rgba` etc were deprecated in favour of the `to_rgba8` etc methods. Maybe you could try running `cargo update` within the repo you're working on and see if that helps?

**Comment by danwilhelm** [comment]
Also note what @mitchmindtree wrote in a PR: "The `NoAvailableAdapter` normally occurs if no device can be found at all - this is more often due to missing the necessary drive (often the Vulkan driver on Linux for example). Can you confirm that changing power preference was what solved your `NoAvailableAdapter` error, and that it wasn't solved by possibly installing a missing graphics driver?"

**Comment by esimov** [comment]
@mitchmindtree `cargo update` fixed the first issue. I assume that I had an older version of nannou previously installed and meantime the dependency library has been updated. 

@danwilhelm unfortunately changing the power adapter to `power_preference(PowerPreference::LowPower)` is still not fixing the issue:

```rust
app.new_window().size(512, 512).view(view).power_preference(PowerPreference::LowPower).build().unwrap();`
```

```bash
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: NoAvailableAdapter', examples/draw/draw_texture.rs:16:100
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by danwilhelm** [comment]
@esimov It may be that you're missing a graphics driver, as @mitchmindtree mentioned in my second comment above. You might just have to install the Vulkan driver, since it appears you're using Linux.

**Comment by esimov** [comment]
@danwilhelm can you explain why nannou requires a Vulkan driver?

**Comment by danwilhelm** [comment]
@esimov Nannou uses wgpu as its backend, which currently only supports Vulkan on Linux (see the Supported Platforms table here: https://github.com/gfx-rs/wgpu).

**Comment by tpltnt** [comment]
Can this issue be closed? Also Ubuntu 16.04 is end-of-life and no longer supported: https://ubuntu.com/16-04

**Comment by esimov** [comment]
It can be closed, but it is still not working on MacOS.
